name: zero_d_c_e_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  camera: ^0.9.4+4
  sliding_up_panel: ^2.0.0+1
  font_awesome_flutter: ^9.2.0
  path_provider: ^2.0.7
  intl: ^0.17.0
  # tflite: ^1.1.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/model/